### ISSUE TITLE
error during installation of toolchain

### ISSUE THREAD

**Issue by YY87927** [proppy/conda-eda#4]
Running into the following issues during installation by running 
`bash ~/Downloads/mixed-signal.gf180mcuc-0-Linux-x86_64.sh -b -p silicon-env/`

Erro message:
concurrent.futures.process._RemoteTraceback:                                                                                                                               
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup
  File "multiprocessing/connection.py", line 256, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 609, in result_iterator
  File "concurrent/futures/_base.py", line 446, in result
  File "concurrent/futures/_base.py", line 391, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[5600] Failed to execute script 'entry_point' due to unhandled exception!

**Comment by YY87927** [comment]
It seems to be caused by insufficient disk space.

**Comment by proppy** [comment]
@YY87927 is it working for you now?

**Comment by YY87927** [comment]
@proppy  No, not yet
The google cloud compute engine ran out space before the installation finished.
